[build]
builder = "nixpacks"

[deploy]
startCommand = "echo 'This is a multi-service project. Please deploy individual services.'"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# This file tells Railway this is a multi-service project
# Deploy individual services from their respective directories 