[build]
builder = "nixpacks"

[deploy]
startCommand = "java -jar target/passwordvault-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 