[build]
builder = "nixpacks"

[deploy]
startCommand = "java -jar target/passwordvault-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 